// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataLink_Parser/frontend/src/main/java/com/frontend/proto/HelloService.proto

package protocomp;

public final class HelloService {
  private HelloService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocomp_TrackMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocomp_TrackMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocomp_TrackRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocomp_TrackRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nLDataLink_Parser/frontend/src/main/java" +
      "/com/frontend/proto/HelloService.proto\022\t" +
      "protocomp\"x\n\014TrackMessage\022\017\n\007trackID\030\001 \001" +
      "(\005\022\024\n\014trackHeading\030\002 \001(\005\022\022\n\ntrackSpeed\030\003" +
      " \001(\005\022\025\n\rtrackLatitude\030\004 \001(\021\022\026\n\016trackLong" +
      "itude\030\005 \001(\021\"\037\n\014TrackRequest\022\017\n\007message\030\001" +
      " \001(\t2F\n\007Greeter\022;\n\005greet\022\027.protocomp.Tra" +
      "ckRequest\032\027.protocomp.TrackMessage\"\000B\002P\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocomp_TrackMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocomp_TrackMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocomp_TrackMessage_descriptor,
        new java.lang.String[] { "TrackID", "TrackHeading", "TrackSpeed", "TrackLatitude", "TrackLongitude", });
    internal_static_protocomp_TrackRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocomp_TrackRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocomp_TrackRequest_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
