// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataLink_Parser/frontend/src/main/java/com/frontend/proto/HelloService.proto

package protocomp;

public interface TrackMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocomp.TrackMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 trackID = 1;</code>
   * @return The trackID.
   */
  int getTrackID();

  /**
   * <code>int32 trackHeading = 2;</code>
   * @return The trackHeading.
   */
  int getTrackHeading();

  /**
   * <code>int32 trackSpeed = 3;</code>
   * @return The trackSpeed.
   */
  int getTrackSpeed();

  /**
   * <code>sint32 trackLatitude = 4;</code>
   * @return The trackLatitude.
   */
  int getTrackLatitude();

  /**
   * <code>sint32 trackLongitude = 5;</code>
   * @return The trackLongitude.
   */
  int getTrackLongitude();
}
