// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataLink_Parser/backend/src/main/java/com/backend/proto/HelloService.proto

package com.backend.protocomp;

public final class HelloServiceOuterClass {
  private HelloServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_backend_protocomp_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_backend_protocomp_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_backend_protocomp_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_backend_protocomp_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nJDataLink_Parser/backend/src/main/java/" +
      "com/backend/proto/HelloService.proto\022\025co" +
      "m.backend.protocomp\"3\n\014HelloRequest\022\021\n\tf" +
      "irstName\030\001 \001(\t\022\020\n\010lastName\030\002 \001(\t\"!\n\rHell" +
      "oResponse\022\020\n\010greeting\030\001 \001(\t2b\n\014HelloServ" +
      "ice\022R\n\005hello\022#.com.backend.protocomp.Hel" +
      "loRequest\032$.com.backend.protocomp.HelloR" +
      "esponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_backend_protocomp_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_backend_protocomp_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_backend_protocomp_HelloRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_com_backend_protocomp_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_backend_protocomp_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_backend_protocomp_HelloResponse_descriptor,
        new java.lang.String[] { "Greeting", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
