// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataLink_Parser/backend/src/main/java/com/backend/proto/HelloService.proto

package com.backend.protocomp;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.backend.protocomp.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   * @return The greeting.
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   * @return The bytes for greeting.
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
