// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataLink_Parser/backend/src/main/java/com/backend/proto/HelloService.proto

package protocomp;

/**
 * Protobuf type {@code protocomp.TrackMessage}
 */
public final class TrackMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocomp.TrackMessage)
    TrackMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TrackMessage.newBuilder() to construct.
  private TrackMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrackMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TrackMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TrackMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            trackID_ = input.readInt32();
            break;
          }
          case 16: {

            trackHeading_ = input.readInt32();
            break;
          }
          case 24: {

            trackSpeed_ = input.readInt32();
            break;
          }
          case 32: {

            trackLatitude_ = input.readSInt32();
            break;
          }
          case 40: {

            trackLongitude_ = input.readSInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protocomp.HelloService.internal_static_protocomp_TrackMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protocomp.HelloService.internal_static_protocomp_TrackMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protocomp.TrackMessage.class, protocomp.TrackMessage.Builder.class);
  }

  public static final int TRACKID_FIELD_NUMBER = 1;
  private int trackID_;
  /**
   * <code>int32 trackID = 1;</code>
   * @return The trackID.
   */
  @java.lang.Override
  public int getTrackID() {
    return trackID_;
  }

  public static final int TRACKHEADING_FIELD_NUMBER = 2;
  private int trackHeading_;
  /**
   * <code>int32 trackHeading = 2;</code>
   * @return The trackHeading.
   */
  @java.lang.Override
  public int getTrackHeading() {
    return trackHeading_;
  }

  public static final int TRACKSPEED_FIELD_NUMBER = 3;
  private int trackSpeed_;
  /**
   * <code>int32 trackSpeed = 3;</code>
   * @return The trackSpeed.
   */
  @java.lang.Override
  public int getTrackSpeed() {
    return trackSpeed_;
  }

  public static final int TRACKLATITUDE_FIELD_NUMBER = 4;
  private int trackLatitude_;
  /**
   * <code>sint32 trackLatitude = 4;</code>
   * @return The trackLatitude.
   */
  @java.lang.Override
  public int getTrackLatitude() {
    return trackLatitude_;
  }

  public static final int TRACKLONGITUDE_FIELD_NUMBER = 5;
  private int trackLongitude_;
  /**
   * <code>sint32 trackLongitude = 5;</code>
   * @return The trackLongitude.
   */
  @java.lang.Override
  public int getTrackLongitude() {
    return trackLongitude_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (trackID_ != 0) {
      output.writeInt32(1, trackID_);
    }
    if (trackHeading_ != 0) {
      output.writeInt32(2, trackHeading_);
    }
    if (trackSpeed_ != 0) {
      output.writeInt32(3, trackSpeed_);
    }
    if (trackLatitude_ != 0) {
      output.writeSInt32(4, trackLatitude_);
    }
    if (trackLongitude_ != 0) {
      output.writeSInt32(5, trackLongitude_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (trackID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, trackID_);
    }
    if (trackHeading_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, trackHeading_);
    }
    if (trackSpeed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, trackSpeed_);
    }
    if (trackLatitude_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(4, trackLatitude_);
    }
    if (trackLongitude_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(5, trackLongitude_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protocomp.TrackMessage)) {
      return super.equals(obj);
    }
    protocomp.TrackMessage other = (protocomp.TrackMessage) obj;

    if (getTrackID()
        != other.getTrackID()) return false;
    if (getTrackHeading()
        != other.getTrackHeading()) return false;
    if (getTrackSpeed()
        != other.getTrackSpeed()) return false;
    if (getTrackLatitude()
        != other.getTrackLatitude()) return false;
    if (getTrackLongitude()
        != other.getTrackLongitude()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRACKID_FIELD_NUMBER;
    hash = (53 * hash) + getTrackID();
    hash = (37 * hash) + TRACKHEADING_FIELD_NUMBER;
    hash = (53 * hash) + getTrackHeading();
    hash = (37 * hash) + TRACKSPEED_FIELD_NUMBER;
    hash = (53 * hash) + getTrackSpeed();
    hash = (37 * hash) + TRACKLATITUDE_FIELD_NUMBER;
    hash = (53 * hash) + getTrackLatitude();
    hash = (37 * hash) + TRACKLONGITUDE_FIELD_NUMBER;
    hash = (53 * hash) + getTrackLongitude();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protocomp.TrackMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocomp.TrackMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocomp.TrackMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocomp.TrackMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocomp.TrackMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocomp.TrackMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocomp.TrackMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocomp.TrackMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocomp.TrackMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protocomp.TrackMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocomp.TrackMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocomp.TrackMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protocomp.TrackMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocomp.TrackMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocomp.TrackMessage)
      protocomp.TrackMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocomp.HelloService.internal_static_protocomp_TrackMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocomp.HelloService.internal_static_protocomp_TrackMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocomp.TrackMessage.class, protocomp.TrackMessage.Builder.class);
    }

    // Construct using protocomp.TrackMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      trackID_ = 0;

      trackHeading_ = 0;

      trackSpeed_ = 0;

      trackLatitude_ = 0;

      trackLongitude_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protocomp.HelloService.internal_static_protocomp_TrackMessage_descriptor;
    }

    @java.lang.Override
    public protocomp.TrackMessage getDefaultInstanceForType() {
      return protocomp.TrackMessage.getDefaultInstance();
    }

    @java.lang.Override
    public protocomp.TrackMessage build() {
      protocomp.TrackMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protocomp.TrackMessage buildPartial() {
      protocomp.TrackMessage result = new protocomp.TrackMessage(this);
      result.trackID_ = trackID_;
      result.trackHeading_ = trackHeading_;
      result.trackSpeed_ = trackSpeed_;
      result.trackLatitude_ = trackLatitude_;
      result.trackLongitude_ = trackLongitude_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protocomp.TrackMessage) {
        return mergeFrom((protocomp.TrackMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protocomp.TrackMessage other) {
      if (other == protocomp.TrackMessage.getDefaultInstance()) return this;
      if (other.getTrackID() != 0) {
        setTrackID(other.getTrackID());
      }
      if (other.getTrackHeading() != 0) {
        setTrackHeading(other.getTrackHeading());
      }
      if (other.getTrackSpeed() != 0) {
        setTrackSpeed(other.getTrackSpeed());
      }
      if (other.getTrackLatitude() != 0) {
        setTrackLatitude(other.getTrackLatitude());
      }
      if (other.getTrackLongitude() != 0) {
        setTrackLongitude(other.getTrackLongitude());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protocomp.TrackMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protocomp.TrackMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int trackID_ ;
    /**
     * <code>int32 trackID = 1;</code>
     * @return The trackID.
     */
    @java.lang.Override
    public int getTrackID() {
      return trackID_;
    }
    /**
     * <code>int32 trackID = 1;</code>
     * @param value The trackID to set.
     * @return This builder for chaining.
     */
    public Builder setTrackID(int value) {
      
      trackID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 trackID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrackID() {
      
      trackID_ = 0;
      onChanged();
      return this;
    }

    private int trackHeading_ ;
    /**
     * <code>int32 trackHeading = 2;</code>
     * @return The trackHeading.
     */
    @java.lang.Override
    public int getTrackHeading() {
      return trackHeading_;
    }
    /**
     * <code>int32 trackHeading = 2;</code>
     * @param value The trackHeading to set.
     * @return This builder for chaining.
     */
    public Builder setTrackHeading(int value) {
      
      trackHeading_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 trackHeading = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrackHeading() {
      
      trackHeading_ = 0;
      onChanged();
      return this;
    }

    private int trackSpeed_ ;
    /**
     * <code>int32 trackSpeed = 3;</code>
     * @return The trackSpeed.
     */
    @java.lang.Override
    public int getTrackSpeed() {
      return trackSpeed_;
    }
    /**
     * <code>int32 trackSpeed = 3;</code>
     * @param value The trackSpeed to set.
     * @return This builder for chaining.
     */
    public Builder setTrackSpeed(int value) {
      
      trackSpeed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 trackSpeed = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrackSpeed() {
      
      trackSpeed_ = 0;
      onChanged();
      return this;
    }

    private int trackLatitude_ ;
    /**
     * <code>sint32 trackLatitude = 4;</code>
     * @return The trackLatitude.
     */
    @java.lang.Override
    public int getTrackLatitude() {
      return trackLatitude_;
    }
    /**
     * <code>sint32 trackLatitude = 4;</code>
     * @param value The trackLatitude to set.
     * @return This builder for chaining.
     */
    public Builder setTrackLatitude(int value) {
      
      trackLatitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 trackLatitude = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrackLatitude() {
      
      trackLatitude_ = 0;
      onChanged();
      return this;
    }

    private int trackLongitude_ ;
    /**
     * <code>sint32 trackLongitude = 5;</code>
     * @return The trackLongitude.
     */
    @java.lang.Override
    public int getTrackLongitude() {
      return trackLongitude_;
    }
    /**
     * <code>sint32 trackLongitude = 5;</code>
     * @param value The trackLongitude to set.
     * @return This builder for chaining.
     */
    public Builder setTrackLongitude(int value) {
      
      trackLongitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 trackLongitude = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrackLongitude() {
      
      trackLongitude_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocomp.TrackMessage)
  }

  // @@protoc_insertion_point(class_scope:protocomp.TrackMessage)
  private static final protocomp.TrackMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protocomp.TrackMessage();
  }

  public static protocomp.TrackMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrackMessage>
      PARSER = new com.google.protobuf.AbstractParser<TrackMessage>() {
    @java.lang.Override
    public TrackMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TrackMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TrackMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrackMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protocomp.TrackMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

